debug: true

env:
    button_number: 8
    channel_number: 3
    window_width: 640
    window_height: 480
    stack_size: 4
    host: 127.0.0.1
    max_retries: 15
    port: 8080

general:
    lr: 2.5e-4
    gamma: 0.99
    gae_lambda: 0.95
    clip_epsilon: 0.2
    entropy_coef: 0.01
    value_loss_coef: 0.5
    max_grad_norm: 0.5

teacherModel:
    rollout_steps: 2048
    minibatch_size: 64
    update_epochs: 4
    num_envs: 16
    batch_size: num_envs * rollout_steps
    episodes: 100
