debug: true

env:
    button_number: 8
    channel_number: 3
    window_width: 640
    window_height: 480
    stack_size: 4
    host: 127.0.0.1
    max_retries: 15
    port: 8080
    trunk_ticks: 20000

general:
    lr: 1.0e-4
    gamma: 0.99
    gae_lambda: 0.95
    clip_epsilon: 0.1
    entropy_coef: 0.01
    value_loss_coef: 0.5
    max_grad_norm: 0.5

teacherModel:
    rollout_steps: 2048
    minibatch_size: 1024
    update_epochs: 4
    num_envs: 4
    batch_size: 8192
    episodes: 1000
    namespace: teacher_model 

studentModel:
    rollout_steps: 256
    minibatch_size: 64
    update_epochs: 4
    num_envs: 4
    batch_size: 8192
    episodes: 1000
    namespace: student_model
    temperature: 2
    dist_coef: 0.3
